### PR TITLE
Render both summary and description in RSS feeds

### PR DESCRIPTION
**Pull request by mmmavis**
Re: comments in PR https://github.com/toolness/planet-badges/pull/4

echo both the summary and description of the original article to the aggregated feed

### CODE REVIEW

**Comment by toolness** [comment]
Yeah!!! I think this is good. Thanks Mavis!

**Comment by mmmavis** [comment]
Awesome!  Thanks, Atul.  Could you let me know when the changes have been pushed live?  (Not urgent)

**Comment by toolness** [comment]
No problem! I think I just pushed the changes life and forced a push to the planet hive s3 bucket... The generated [rss feed](http://planet.hivelearningnetworks.org/rss) does seem to contain both `<summary>` and `<description>` elements so I think things are working okay, but let me know if they're not!

**Comment by mmmavis** [comment]
It works well. Thanks!

**Pull request merged**
