### PR TITLE
updated build.js to make nicer rss feeds

### PR DESCRIPTION
**Pull request by cmcavoy**
Actually works now.

### CODE REVIEW

**Comment by toolness** [comment]
This looks good, commit at will!!! (I added you as collaborator so you can merge yourself.)

**Comment by cmcavoy** [comment]
GROSS SPACE REMOVED. merging.

**Comment by cmcavoy** [comment]
Thanks for the commit access...where does this run? Does it deploy on a
commit hook?

On Tue, Nov 26, 2013 at 9:43 AM, Atul Varma notifications@github.comwrote:

> This looks good, commit at will!!! (I added you as collaborator so you can
> merge yourself.)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/toolness/planet-badges/pull/3#issuecomment-29302651
> .

## 

@chmcavoy http://twitter.com/chmcavoy
http://lonelylion.com

**Comment by toolness** [comment]
Nope, it doesn't deploy on a commit hook... I assigned you as a collaborator a while ago, can you access https://dashboard.heroku.com/apps/planet-openbadges-org ?

Just push to that app and then it will start working.

**Pull request merged**
